app = "bwets"

[build]
  dockerfile = "Dockerfile"

# delete the whole [deploy] section
# [deploy]
#   release_command = "python scripts/refresh_entities.py"

[[services]]
  internal_port = 8080
  protocol      = "tcp"
  processes     = ["app"]
  [[services.ports]]
    handlers = ["http"]
    port     = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port     = 443

  [services.concurrency]
    # allow one in-flight connection while the app warms up
    soft_limit = 25
    hard_limit = 50

[checks]
  [checks.http]
    port = 8080
    type = "http"
    interval = "30s"
    grace_period = "1m"   # gives the refresher up to 60 s
    method = "get"
    path = "/"

[mounts]
  source      = "data"   # name created by Fly
  destination = "/data"
